namespace CvsChecker.Library.Helpers;

public enum CsvIssueType
{
	BLANK_ROW,
	COLUMN_TYPE_INSTABILITY,
	CSV_PARSE_FAILED,
	DUPLICATE_HEADER,
	HEADER_EMPTY,
	INCONSISTENT_QUOTING,
	INVALID_DATE,
	MIXED_LINE_ENDINGS,
	ROW_WIDTH_MISMATCH,
	TRAILING_DELIMITER_HEADER,
	TRAILING_DELIMITER_ROW,
	UNCLOSED_QUOTE,
	UTF8_BOM,
	WHITESPACE_IN_HEADERS,
}
